# Generated by Django 4.2.4 on 2023-08-31 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_date_task_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descricaoo',
            new_name='descricao',
        ),
    ]
