# Generated by Django 4.2.4 on 2023-09-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cliente_reclamacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Reclamacao',
        ),
        migrations.AddField(
            model_name='cliente',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='reclamacao',
            field=models.TextField(null=True),
        ),
    ]
