# Generated by Django 4.2.4 on 2023-09-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_cliente_reclamacao_cliente_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='data',
            new_name='data_prevista',
        ),
    ]
