# Generated by Django 4.2.4 on 2023-09-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_data_cliente_data_prevista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_prevista',
        ),
        migrations.AddField(
            model_name='cliente',
            name='dataPrevista',
            field=models.DateField(null=True),
        ),
    ]
