# Generated by Django 4.2.4 on 2023-09-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_cliente_data_prevista_cliente_dataprevista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='reclamacao',
        ),
        migrations.AddField(
            model_name='cliente',
            name='anotacaoes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pedido',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
