# Generated by Django 4.2.4 on 2023-09-02 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_cliente_assunto_remove_cliente_reclamacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='anotacaoes',
            new_name='anotacoes',
        ),
    ]
