# Generated by Django 4.2.4 on 2023-09-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_anotacaoes_cliente_anotacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(null=True),
        ),
    ]
